export const courses = [
  {
    category: "TECHNOLOGY",
    title: "Introduction to Python Programming",
    price: 269.99,
    rating: 4.2,
    reviewCount: 2456,
    studentCount: "180k",
    instructor: "Jayvon Simon",
    duration: "60 hours",
    level: "Beginner",
    description:
      "Learn the basics of Python programming, including syntax, data types, and control structures.",
    imageUrl: "/assets/image/course.webp", // Replace with actual image URL
  },
  {
    category: "HEALTH AND WELLNESS",
    title: "Digital Marketing Fundamentals",
    price: 159.99,
    rating: 3.7,
    reviewCount: 1288,
    studentCount: "144k",
    instructor: "Harrison Stein",
    duration: "120 hours",
    level: "Intermediate",
    imageUrl: "/assets/image/course.webp",
    description:
      "Learn the basics of Python programming, including syntax, data types, and control structures.",
  },
  {
    category: "TRAVEL",
    title: "Data Science with R",
    originalPrice: 89.99,
    discountedPrice: 269.99,
    rating: 4.5,
    reviewCount: 3112,
    studentCount: "188k",
    instructor: "Linney Davidson",
    duration: "90 hours",
    level: "Expert",
    imageUrl: "/assets/image/course.webp",
    description:
      "Learn the basics of Python programming, including syntax, data types, and control structures.",
  },
  {
    category: "BUSINESS",
    title: "Web Development Bootcamp",
    price: 199.99,
    rating: 4.8,
    reviewCount: 5123,
    studentCount: "200k",
    instructor: "Jayvon Simon",
    duration: "80 hours",
    level: "Beginner",
    imageUrl: "/assets/image/course.webp",
    description:
      "Learn the basics of Python programming, including syntax, data types, and control structures.",
  },
  {
    category: "MARKETING",
    title: "Graphic Design Masterclass",
    price: 129.99,
    rating: 4.0,
    reviewCount: 987,
    studentCount: "90k",
    instructor: "Harrison Stein",
    duration: "70 hours",
    level: "Intermediate",
    imageUrl: "/assets/image/course.webp",
    description:
      "Learn the basics of Python programming, including syntax, data types, and control structures.",
  },
  {
    category: "FINANCE",
    title: "Machine Learning A-Z™",
    price: 299.99,
    rating: 4.9,
    reviewCount: 1500,
    studentCount: "250k",
    instructor: "Linney Davidson",
    duration: "100 hours",
    level: "Expert",
    imageUrl: "/assets/image/course.webp",
    description:
      "Learn the basics of Python programming, including syntax, data types, and control structures.",
  },
];
