import type { Metadata } from "next";
import "./globals.css";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="min-h-screen w-full">{children}</body>
    </html>
  );
};

export default RootLayout;
export { metadata };
